version: '3.3'
services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: cameldb
      POSTGRES_USER: camel
      POSTGRES_PASSWORD: camel
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

    networks:
      - reference
networks:
  reference: